//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DapperMagazaWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UPhone { get; set; }
        public string UMail { get; set; }
        public string UPassword { get; set; }
        public string UAddress { get; set; }
    }
}
